version: "3.8"

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:4.2.0
    ports:
      - "54286:54286"
    volumes:
      - ./nest-volume/desktop:/home/nest

  nest-server:
    image: nest/nest-simulator:3.9
    environment:
      NEST_CONTAINER_MODE: nest-server
    ports:
      - "52425:52425"
    volumes:
      - ./nest-volume/nestml:/tmp/nestmlmodules

  # nestml-server:
  #   image: nest/nest-simulator:3.9
  #   environment:
  #     NEST_CONTAINER_MODE: nestml-server
  #   ports:
  #     - "52426:52426"
  #   volumes:
  #     - ./nest-volume/nestml:/tmp/nestmlmodules
